// File generated by FlutterFire CLI.
// Run: flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
// Then replace this file with the generated output.
//
// ────────────────────────────────────────────────────────────────
// IMPORTANT: This is a placeholder. You MUST run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
// to generate this file with your real Firebase project values.
// ────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported on Linux. '
          'Run flutterfire configure to generate platform-specific options.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported on this platform.',
        );
    }
  }

  // ── REPLACE ALL VALUES BELOW with your Firebase project config ──

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAllIidpC3_G4pzvOLZyEyU32THJzisos',
    appId: '1:907333622939:web:565a3cd36630b863ce3a3e',
    messagingSenderId: '907333622939',
    projectId: 'smartresume-7601e',
    authDomain: 'smartresume-7601e.firebaseapp.com',
    storageBucket: 'smartresume-7601e.firebasestorage.app',
    measurementId: 'G-TBEMKBRV2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPgcVYbmY2FzfNyMMHf7eENaga8IU5_FQ',
    appId: '1:907333622939:android:1125c914021097b8ce3a3e',
    messagingSenderId: '907333622939',
    projectId: 'smartresume-7601e',
    storageBucket: 'smartresume-7601e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWmJVD8ruhUSdW2DNfWcNut5znRiFlvz8',
    appId: '1:907333622939:ios:1c9b914479649e6fce3a3e',
    messagingSenderId: '907333622939',
    projectId: 'smartresume-7601e',
    storageBucket: 'smartresume-7601e.firebasestorage.app',
    iosClientId: '907333622939-g20qd3nmdb9n7kosatpmj50p1eg7n9nl.apps.googleusercontent.com',
    iosBundleId: 'com.aicareer.aiCareerOs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.aicareer.aiCareerOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}